import Head from 'next/head'
import AddProfileScreen from '../Components/UserProfileManagementScreens/AddProfileScreen'
import SideBar from '../Components/Basics/SideBar'
import Topnav from '../Components/Basics/Topnav'

export default function AddProfileManage() {
    return (
        <>
            <Head>
                <title>LeadShyne</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="main_wrapper">
                <Topnav />
                <div className="content_wrapper">
                    <SideBar isactive='adminuser' />
                    <AddProfileScreen />
                </div>
            </main>
        </>
    )
}
